### ISSUE TITLE
module declares its path as: appliedgo.net/what 	        but was required as: github.com/appliedgocode/what

### ISSUE THREAD

**Issue by forging2012** [appliedgocode/what#2]
```
➜  ~ go get github.com/appliedgocode/what
go: github.com/appliedgocode/what upgrade => v0.1.1
go get: github.com/appliedgocode/what@v0.1.1: parsing go.mod:
	module declares its path as: appliedgo.net/what
	        but was required as: github.com/appliedgocode/what
```

**Comment by christophberger** [comment]
Hi @forging2012 , this is actually a doc bug in the README. The error message is expected behavior. `appliedgo.net/what` is a vanity import path that redirects to the repo. Read the details [here](https://golang.org/cmd/go/#hdr-Remote_import_paths). 

I fixed the Readme.

**Comment by forging2012** [comment]
import "appliedgo.net/what"
This way is not a common use style.
In github, It usuaIIy  is 
import "github.com/appliedgocode/what" 
will be better.
I suggest.

**Comment by christophberger** [comment]
Thank you for sharing your thoughts. However, vanity import paths are supported in Go since a long time, and are already used widely. Notable examples are:

* rsc.io/pdf
* knative.dev/pkg
* gocloud.dev
* contrib.go.opencensus.io/exporter/jaeger
* gobot.io/x/gobot
* go.uber.org/zap
* cloud.google.com/go

Vanity import paths have two particular advantages:
* The author can choose a short and easy-to-remember path
* The repository is not bound to a particular repo hosting service

Further reading: 
* [Vanity import paths in Go](https://sagikazarmark.hu/blog/vanity-import-paths-in-go/)
* [Vanity Go Import Paths](https://blog.bramp.net/post/2017/10/02/vanity-go-import-paths/)
* [Vanity Imports with Hugo · npf.io](https://npf.io/2016/10/vanity-imports-with-hugo/)
